components:
  responses:
    getUrl:
      content:
        application/json:
          examples:
            example:
              value:
                userInfo: PlPY81WkHVqy+FAtUKs8vQXqXTRcsChw1KaEDB22DlTc3eN1IG3mr0759oOX5dCl6weacHMIBD6OtXGGmvslCA==
          schema:
            $ref: '#/components/schemas/getUrlResponse'
      description: Get url response
  schemas:
    getUrlResponse:
      description: Get url response
      format: encrypted using AES128, AES192 or AES256
      properties:
        balance:
          description: Part of the Cardinfo scope
          type: string
        cardnumber:
          description: Part of the Cardinfo scope
          type: string
        email:
          description: Part of the Email scope
          type: string
        email_verified:
          description: Part of the Email scope
          type: boolean
        family_name:
          description: Part of the Profile scope
          type: string
        given_name:
          description: Part of the Profile scope
          type: string
        locale:
          description: Part of the Locale scope
          type: string
        middle_name:
          description: Part of the Profile scope
          type: string
        name:
          description: Part of the Profile scope
          type: string
        nickname:
          description: Part of the Profile scope
          type: string
        picture:
          description: Part of the Profile scope
          type: string
        secret:
          description: PIN or security code of the (gift)card, part of the Secret
            scope.
          type: string
        updated_at:
          description: Part of the Profile scope
          type: string
      type: object
    secret:
      description: Secret used to encrypt the User Info.
      example: KWpreJjLJR6_Q0W8-v_oSiF95_Fyoe7O4MTo1tghELk
      format: Base64 URL encoded
      type: string
    url:
      description: User Info Url.
      example: https://card.dolden.net/ecards/v1/pub/dataExchange/SCXPNE2I3D4JU5NWDDTAXRCBBEJQWJX5
      format: url
      type: string
info:
  description: User Info API for websites
  externalDocs:
    description: Find more info here
    url: https://dappre.com
  license:
    name: (c) Dappre BV 2019 - All rights reserved
    url: https://dappre.com
  title: User Info API - Website
  version: 1.0.0
openapi: 3.0.0
paths:
  /{WebsitePath}:
    get:
      description: Website call from eCard
      operationId: Website call
      responses:
        '200':
          description: Website page
      tags:
      - Website
    parameters:
    - description: Website path, for example 'webshop' for the website 'https://example.com/webshop'.
      in: path
      name: WebsitePath
      required: true
    - description: secret
      in: query
      name: s_
      schema:
        $ref: '#/components/schemas/secret'
    - description: User Info Url
      in: query
      name: url_
      schema:
        $ref: '#/components/schemas/url'
    servers:
    - description: Website
      url: '{WebsiteBaseUrl}'
      variables:
        WebsiteBaseUrl:
          default: https://example.com/webshop
          description: Website base url
  /{urlPath}:
    get:
      description: Get encrypted User Info
      operationId: Get encrypted User Info
      responses:
        '200':
          $ref: '#/components/responses/getUrl'
      tags:
      - User Info
    parameters:
    - description: Path part of url as passed in url_ query parameter
      in: path
      name: urlPath
      required: true
    servers:
    - description: User Info Endpoint
      url: '{urlBase}'
      variables:
        UserInfoBaseUrl:
          default: https://card.dolden.net
          description: Base part of url as passed in url_ query parameter
